### ISSUE TITLE
How to convert pkl to pb on windows?

### ISSUE THREAD

**Issue by wodsoe** [nolan-dev/GANInterface#15]
Hi,
How to convert pkl to pb on windows?
Thank you!

**Comment by nolan-dev** [comment]
Hey sorry for the late reply, been busy and haven't had time to work on/support this project.
You could try the steps here: https://github.com/nolan-dev/GANInterface/tree/master/pkl_conversion.  Unfortunately, it's very hacky and more complicated than it should be, but it's the fastest thing I could get working.

**Comment by wodsoe** [comment]
OK.Thank you!
