### ISSUE TITLE
[Question] GPU Utilization?

### ISSUE THREAD

**Issue by BiatuAutMiahn** [nolan-dev/GANInterface#7]
I have a RTX 2070, how can I use tensorflow-gpu

**Comment by nolan-dev** [comment]
Hey sorry for the super late reply.  Unfortunately, I haven't really looked much into using the a GPU for the tool, though Klanly mentioned substituting the dll worked in this issue: https://github.com/nolan-dev/GANInterface/issues/4#issue-545841072.  The tensorflow.dll included with the tool only works for the CPU.

**Comment by BiatuAutMiahn** [comment]
ah ok, thank you
